#!/bin/bash

command="$1"
case "${command}" in
  generate_nuget_config)
      cat << EOF > ~/.nuget/NuGet/NuGet.Config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nancy-myget" value="https://www.myget.org/F/nancyfx/api/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
EOF
      exit $?
      ;;
  build)
      dotnet build --configuration=Release
      exit $?
      ;;
  utest)
      # run unit tests
      dotnet test --configuration=Release --filter Category!=integration ./tests/CryptoDownloaderConsole.Tests/
      exit $?
      ;;
  itest)
      # run integration tests
      dotnet test --configuration=Release --filter Category=integration ./tests/CryptoDownloaderConsole.Tests/
      exit $?
      ;;
  atest)
      # run acceptance tests
      bats tests/acceptance/bats
      exit $?
      ;;
  run)
      dotnet run --project=./src/CryptoDownloaderConsole/
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
